/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package automatmp;

/**
 *
 * @author admin
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
        inviRocketMars();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void inviRocketMars(){
        
        //Mars
        marsGrain.setOpaque(false);
        marsGrain.setContentAreaFilled(false);
        marsGrain.setBorderPainted(false);
        marsGrain.setText("");
        
        marsCow.setOpaque(false);
        marsCow.setContentAreaFilled(false);
        marsCow.setBorderPainted(false);
        marsCow.setText("");
        
        marsLion.setOpaque(false);
        marsLion.setContentAreaFilled(false);
        marsLion.setBorderPainted(false);
        marsLion.setText("");
        
        marsHuman.setOpaque(false);
        marsHuman.setContentAreaFilled(false);
        marsHuman.setBorderPainted(false);
        marsHuman.setText("");
        
        marsSavage.setOpaque(false);
        marsSavage.setContentAreaFilled(false);
        marsSavage.setBorderPainted(false);
        marsSavage.setText("");
        
        marsScientist.setOpaque(false);
        marsScientist.setContentAreaFilled(false);
        marsScientist.setBorderPainted(false);
        marsScientist.setText("");
        
        //Rocket
        rocketGrain.setOpaque(false);
        rocketGrain.setContentAreaFilled(false);
        rocketGrain.setBorderPainted(false);
        rocketGrain.setText("");
        
        rocketCow.setOpaque(false);
        rocketCow.setContentAreaFilled(false);
        rocketCow.setBorderPainted(false);
        rocketCow.setText("");
        
        rocketLion.setOpaque(false);
        rocketLion.setContentAreaFilled(false);
        rocketLion.setBorderPainted(false);
        rocketLion.setText("");
        
        rocketHuman.setOpaque(false);
        rocketHuman.setContentAreaFilled(false);
        rocketHuman.setBorderPainted(false);
        rocketHuman.setText("");
        
        rocketSavage.setOpaque(false);
        rocketSavage.setContentAreaFilled(false);
        rocketSavage.setBorderPainted(false);
        rocketSavage.setText("");
        
        rocketScientist.setOpaque(false);
        rocketScientist.setContentAreaFilled(false);
        rocketScientist.setBorderPainted(false);
        rocketScientist.setText("");
    
//    rocketGrain.setVisible(false);
//    rocketCow.setVisible(false);
//    rocketLion.setVisible(false);
//    rocketHuman.setVisible(false);
//    rocketScientist.setVisible(false);
//    rocketSavage.setVisible(false);
//    marsGrain.setVisible(false);
//    marsCow.setVisible(false);
//    marsLion.setVisible(false);
//    marsHuman.setVisible(false);
//    marsScientist.setVisible(false);
//    marsSavage.setVisible(false);
    
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        earthPanel = new javax.swing.JPanel();
        earthGrain = new javax.swing.JButton();
        earthLion = new javax.swing.JButton();
        earthCow = new javax.swing.JButton();
        earthScientist = new javax.swing.JButton();
        earthSavage = new javax.swing.JButton();
        earthHuman = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rocketTransport = new javax.swing.JButton();
        rocketPanel = new javax.swing.JPanel();
        rocketGrain = new javax.swing.JButton();
        rocketLion = new javax.swing.JButton();
        rocketCow = new javax.swing.JButton();
        rocketHuman = new javax.swing.JButton();
        rocketSavage = new javax.swing.JButton();
        rocketScientist = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        earthPanel1 = new javax.swing.JPanel();
        marsGrain = new javax.swing.JButton();
        marsLion = new javax.swing.JButton();
        marsCow = new javax.swing.JButton();
        marsScientist = new javax.swing.JButton();
        marsSavage = new javax.swing.JButton();
        marsHuman = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Game");

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mars:");

        earthGrain.setText("Grain");
        earthGrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earthGrainActionPerformed(evt);
            }
        });

        earthLion.setText("Lion");
        earthLion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earthLionActionPerformed(evt);
            }
        });

        earthCow.setText("Cow");
        earthCow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earthCowActionPerformed(evt);
            }
        });

        earthScientist.setText("Scientist");
        earthScientist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                earthScientistActionPerformed(evt);
            }
        });

        earthSavage.setText("Savage");
        earthSavage.setActionCommand("Savage");

        earthHuman.setText("Human");

        javax.swing.GroupLayout earthPanelLayout = new javax.swing.GroupLayout(earthPanel);
        earthPanel.setLayout(earthPanelLayout);
        earthPanelLayout.setHorizontalGroup(
            earthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(earthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(earthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(earthGrain, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(earthLion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(earthCow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(earthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(earthScientist, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(earthSavage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(earthHuman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        earthPanelLayout.setVerticalGroup(
            earthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(earthPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(earthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(earthGrain)
                    .addComponent(earthHuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(earthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(earthLion)
                    .addComponent(earthSavage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(earthPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(earthCow)
                    .addComponent(earthScientist))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Earth:");

        rocketTransport.setText("Transport");
        rocketTransport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rocketTransportActionPerformed(evt);
            }
        });

        rocketGrain.setText("Grain");

        rocketLion.setText("Lion");

        rocketCow.setText("Cow");

        rocketHuman.setText("Human");
        rocketHuman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rocketHumanActionPerformed(evt);
            }
        });

        rocketSavage.setText("Savage");

        rocketScientist.setText("Scientist");

        javax.swing.GroupLayout rocketPanelLayout = new javax.swing.GroupLayout(rocketPanel);
        rocketPanel.setLayout(rocketPanelLayout);
        rocketPanelLayout.setHorizontalGroup(
            rocketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rocketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rocketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rocketLion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rocketCow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rocketGrain, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rocketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(rocketSavage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rocketScientist, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                    .addComponent(rocketHuman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        rocketPanelLayout.setVerticalGroup(
            rocketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rocketPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rocketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rocketHuman)
                    .addComponent(rocketGrain, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(rocketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rocketLion)
                    .addComponent(rocketSavage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(rocketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rocketCow)
                    .addComponent(rocketScientist))
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Rocket:");

        marsGrain.setText("Grain");
        marsGrain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marsGrainActionPerformed(evt);
            }
        });

        marsLion.setText("Lion");
        marsLion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marsLionActionPerformed(evt);
            }
        });

        marsCow.setText("Cow");
        marsCow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marsCowActionPerformed(evt);
            }
        });

        marsScientist.setText("Scientist");
        marsScientist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marsScientistActionPerformed(evt);
            }
        });

        marsSavage.setText("Savage");

        marsHuman.setText("Human");

        javax.swing.GroupLayout earthPanel1Layout = new javax.swing.GroupLayout(earthPanel1);
        earthPanel1.setLayout(earthPanel1Layout);
        earthPanel1Layout.setHorizontalGroup(
            earthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(earthPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(earthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(marsGrain, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                    .addComponent(marsLion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marsCow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(earthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marsScientist, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(marsSavage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(marsHuman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        earthPanel1Layout.setVerticalGroup(
            earthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(earthPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(earthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marsGrain)
                    .addComponent(marsHuman))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(earthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(marsLion)
                    .addComponent(marsSavage))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(earthPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(marsScientist)
                    .addComponent(marsCow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(earthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rocketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(rocketTransport)
                        .addGap(13, 13, 13)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(earthPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap(427, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(earthPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(rocketTransport)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rocketPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(earthPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rocketTransportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rocketTransportActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rocketTransportActionPerformed

    private void earthGrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earthGrainActionPerformed
        // TODO add your handling code here:
        earthGrain.setOpaque(false);
        earthGrain.setContentAreaFilled(false);
        earthGrain.setBorderPainted(false);
        earthGrain.setText("");
        
        rocketGrain.setOpaque(true);
        rocketGrain.setContentAreaFilled(true);
        rocketGrain.setBorderPainted(true);
        rocketGrain.setText("Grain");
    }//GEN-LAST:event_earthGrainActionPerformed

    private void earthLionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earthLionActionPerformed
        // TODO add your handling code here:
        earthLion.setOpaque(false);
        earthLion.setContentAreaFilled(false);
        earthLion.setBorderPainted(false);
        earthLion.setText("");
        
        rocketLion.setOpaque(true);
        rocketLion.setContentAreaFilled(true);
        rocketLion.setBorderPainted(true);
        rocketLion.setText("Lion");
    }//GEN-LAST:event_earthLionActionPerformed

    private void earthCowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earthCowActionPerformed
        // TODO add your handling code here:
        earthCow.setOpaque(false);
        earthCow.setContentAreaFilled(false);
        earthCow.setBorderPainted(false);
        earthCow.setText("");
        
        rocketCow.setOpaque(true);
        rocketCow.setContentAreaFilled(true);
        rocketCow.setBorderPainted(true);
        rocketCow.setText("Cow");
    }//GEN-LAST:event_earthCowActionPerformed

    private void earthScientistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_earthScientistActionPerformed
        // TODO add your handling code here:
        earthScientist.setOpaque(false);
        earthScientist.setContentAreaFilled(false);
        earthScientist.setBorderPainted(false);
        earthScientist.setText("");
        
        rocketScientist.setOpaque(true);
        rocketScientist.setContentAreaFilled(true);
        rocketScientist.setBorderPainted(true);
        rocketScientist.setText("Cow");
    }//GEN-LAST:event_earthScientistActionPerformed

    private void marsGrainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marsGrainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marsGrainActionPerformed

    private void marsLionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marsLionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marsLionActionPerformed

    private void marsCowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marsCowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marsCowActionPerformed

    private void marsScientistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marsScientistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_marsScientistActionPerformed

    private void rocketHumanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rocketHumanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rocketHumanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton earthCow;
    private javax.swing.JButton earthGrain;
    private javax.swing.JButton earthHuman;
    private javax.swing.JButton earthLion;
    private javax.swing.JPanel earthPanel;
    private javax.swing.JPanel earthPanel1;
    private javax.swing.JButton earthSavage;
    private javax.swing.JButton earthScientist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton marsCow;
    private javax.swing.JButton marsGrain;
    private javax.swing.JButton marsHuman;
    private javax.swing.JButton marsLion;
    private javax.swing.JButton marsSavage;
    private javax.swing.JButton marsScientist;
    private javax.swing.JButton rocketCow;
    private javax.swing.JButton rocketGrain;
    private javax.swing.JButton rocketHuman;
    private javax.swing.JButton rocketLion;
    private javax.swing.JPanel rocketPanel;
    private javax.swing.JButton rocketSavage;
    private javax.swing.JButton rocketScientist;
    private javax.swing.JButton rocketTransport;
    // End of variables declaration//GEN-END:variables
}
